export const open_source_topics = [
  { title: "C", className: "c" },
  { title: "Javascript", className: "javascript" },
  { title: "Go", className: "go" },
  { title: "Ruby", className: "ruby" },
  { title: "Python", className: "python" },
];

export const topics = [
  {
    title: "Development",
    className: "development",
    children: [
      { title: "Devops", className: "javascript" },
      { title: "Databases", className: "c" },
      { title: "Apis", className: "go" },
      { title: "Libraries", className: "ruby" },
    ],
  },
  {
    title: "System",
    className: "system",
    children: [
      { title: "Security", className: "c" },
      { title: "Cloud", className: "javascript" },
      { title: "Apple", className: "go" },
    ],
  },
  {
    title: "Tools",
    className: "tools",
    children: [
      { title: "Productivity", className: "c" },
    ],
  },
  {
    title: "Data Science",
    className: "data-science",
  },
  {
    title: "Blockchain",
    className: "blockchain",
  },
  {
    title: "Mobile",
    className: "mobile",
  },
  {
    title: "Awesome Lists",
    className: "list",
  },
  {
    title: "Social",
    className: "social",
  },
  {
    title: "Visual",
    className: "visual",
  },
  {
    title: "Open source",
    className: "open-source",
    children: [
      { title: "C", className: "c" },
      { title: "Javascript", className: "javascript" },
      { title: "Go", className: "go" },
      { title: "Ruby", className: "ruby" },
      { title: "Python", className: "python" },
    ],
  },
  { title: "All topics", className: "all" },
];

export const articles = {
  data: [
    {
      id: "16219153",
      title: "hackerrank.com",
      desc: "2018 Developer Skills Report",
      author: "_ao789",
      votes: "9",
      date: "1516752527",
      link: "https://research.hackerrank.com/developer-skills/2018/",
      comments: "0",
      tags: "media",
      featured: "1",
    },
    {
      desc: "AI-powered robot finds common soap ingredient may combat malaria",
      tags: "productivity,tools",
      votes: "2",
      author: "neomatrix",
      date: "1516755023",
      title: "engadget.com",
      link:
        "https://www.engadget.com/2018/01/22/ai-powered-robot-common-chemical-combat-malaria/",
      comments: "0",
      id: "16219384",
    },
    {
      desc: "Adobe updates Photoshop with magical AI-powered selection tool",
      date: "1516755340",
      author: "neomatrix",
      title: "thenextweb.com",
      votes: "1",
      comments: "0",
      link:
        "https://thenextweb.com/apps/2018/01/23/adobe-updates-photoshop-magical-ai-powered-selection-tool/",
      id: "16219417",
      tags: "system",
    },
    {
      id: "16219458",
      title: "undux?",
      desc: "Dead simple state management for React",
      author: "bcherny",
      votes: "4",
      date: "1516755816",
      link: "https://github.com/bcherny/undux?",
      comments: "0",
      tags: "web,open-source,typescript",
    },
    {
      id: "16220271",
      title: "prerendercloud-lambda-edge",
      desc: "Pre-render JavaScript apps on CloudFront",
      author: "jotto",
      votes: "4",
      date: "1516767434",
      link: "https://github.com/sanfrancesco/prerendercloud-lambda-edge",
      comments: "0",
      tags: "cloud,productivity,open-source,javascript,system,tools",
    },
    {
      id: "16220333",
      title: "airtime.site",
      desc: "Free-fall detection on mobile web browsers",
      author: "bwasti",
      votes: "2",
      date: "1516768458",
      link: "http://airtime.site",
      comments: "0",
      tags: "data-science,library,development",
    },
    {
      id: "16220640",
      title: "ENTR101",
      desc: "A resource hub for startups",
      author: "johnhorsema",
      votes: "1",
      date: "1516773167",
      link: "http://entr101.surge.sh",
      comments: "0",
      tags: "media",
    },
    {
      desc: "Cross-Region Google Cloud Datastore Replication Using AppEngine",
      tags: "devops,database,open-source,go,makefile,development",
      votes: "3",
      author: "leighmcculloch",
      date: "1516780961",
      title: "google-cloud-appengine-datastore-replicator",
      link:
        "https://github.com/leighmcculloch/google-cloud-appengine-datastore-replicator",
      comments: "0",
      id: "16221132",
    },
    {
      id: "16221534",
      title: "barebones",
      desc: "Barebones multiboot kernel",
      author: "fwsgonzo",
      votes: "1",
      date: "1516787669",
      link: "https://github.com/fwsGonzo/barebones",
      comments: "0",
      tags: "development,open-source,c,assembly",
    },
    {
      id: "16222200",
      title: "producthunt.com",
      desc: "No-code back end template to deploy back ends up to 10x faster",
      author: "onvel",
      votes: "2",
      date: "1516797222",
      link: "https://www.producthunt.com/posts/zeroqode-backend",
      comments: "0",
      tags: "library,example,development",
    },
    {
      id: "16222357",
      title: "burgeramtapp.com",
      desc: "Speed up Berlin Bürgeramt termin hunting",
      author: "256cats",
      votes: "2",
      date: "1516799416",
      link: "https://burgeramtapp.com/",
      comments: "2",
      tags: "development",
    },
    {
      id: "16222480",
      title: "Zero service wait time",
      desc: "graph your furnace. (ondemandtuneup.com)",
      author: "pdp2907",
      votes: "2",
      date: "1516800885",
      link: "http://ondemandtuneup.com",
      comments: "0",
      tags: "cloud,system,system",
    },
    {
      desc:
        "A Browser-based cryptocurrency using React/Redux and P2P connections",
      tags: "security,system",
      votes: "6",
      author: "jeffbarg",
      date: "1516803155",
      title: "littlecoin.io",
      link: "https://littlecoin.io/",
      comments: "1",
      id: "16222752",
    },
    {
      id: "16222942",
      title: "Go-micro",
      desc: "a pluggable RPC framework",
      author: "chuhnk",
      votes: "1",
      date: "1516804382",
      link: "https://github.com/micro/go-micro",
      comments: "0",
      tags: "library,open-source,go,development",
    },
    {
      id: "16223552",
      title: "mycointracker.io",
      desc: "[My Coin Tracker] Crypto Portfolio Tracker",
      author: "enjoibp3",
      votes: "1",
      date: "1516808901",
      link: "https://mycointracker.io",
      comments: "0",
      tags: "blockchain",
    },
    {
      id: "16223586",
      title: "MakerSession",
      desc: "automatically blocks out time on your calendar to GSD",
      author: "floodfx",
      votes: "1",
      date: "1516809112",
      link: "https://makersession.com/?utm_source=showhn",
      comments: "0",
      tags: "design",
    },
  ],
};
